import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const candidate='versions/chs-home-school-evelyn-v1';
const baseline='535da1c94ac5ef0978fa5346fb3c50e65340f06c';
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const json=file=>JSON.parse(read(file));
const before=file=>JSON.parse(execFileSync('git',['show',`${baseline}:${file}`],{cwd:root,encoding:'utf8',maxBuffer:32e6}));
const hash=file=>createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
const words=s=>String(s).toLowerCase().replace(/[’']/g,'').match(/[a-z]+/g);
const audioPath=`${candidate}/data/home_school_audio_manifest.json`,contextPath=`${candidate}/data/home_school_context_manifest.json`;
const audio=json(audioPath),oldAudio=before(audioPath),context=json(contextPath),oldContext=before(contextPath);
const restoredAudio=structuredClone(audio),restoredContext=structuredClone(context);
const receipt=json(`${candidate}/data/question_audio_revision_r26.json`),screen=json(`${candidate}/review/r26-audio/screening.json`);
assert.equal(receipt.revision,'r26-clear-at-school-kid-questions');
assert.equal(receipt.files.length,2);
assert.deepEqual(receipt.files.map(c=>c.event),['HUG','HELP']);
assert.equal(receipt.voice,'Evelyn');assert.equal(receipt.style,'Soft');assert.equal(receipt.speed,.9);
assert.match(receipt.processing,/Byte-for-byte whole-sentence/);
assert.match(receipt.listeningReview,/researcher naturalness preview required before submission/);
assert.equal(screen.audioUploaded,false);assert.equal(screen.expectedCaptionsProvidedToModel,false);
assert.equal(screen.clips.length,2);
for(const clip of receipt.files){
  assert.equal(clip.context,'SCHOOL');assert.equal(clip.recipient,'KID');
  assert.match(clip.output,/^assets\/home_school\/generated\/audio\/hs_r26_00[12]_school_kid_(hug|help)_question_clear_at\.mp3$/);
  assert.equal(hash(clip.output),clip.sha256);assert.equal(fs.statSync(path.join(root,clip.output)).size,clip.bytes);
  if(fs.existsSync(path.join(root,clip.source)))assert.equal(hash(clip.source),clip.sha256);
  assert.equal(hash(clip.replaces.output),clip.replaces.sha256,'Original recording must stay immutable');
  assert.equal(clip.sampleRateHz,44100);assert.equal(clip.channels,1);
  assert.equal(clip.encodedBytesIdenticalToSource,true);assert.equal(clip.fullScaleClippedSamples,0);
  assert.ok(clip.decodedPeakDbfs < -3.8 && clip.decodedPeakDbfs > -4.2);
  assert.equal(clip.join,'not_applicable_whole_sentence');
  const check=screen.clips.find(c=>c.output===clip.output);assert.ok(check);assert.equal(check.sha256,clip.sha256);
  assert.equal(check.wordsMatch,true);assert.equal(check.startsWithAt,true);
  assert.deepEqual(words(check.transcript),words(clip.text));
  assert.deepEqual(check.internalSilencesOver400ms,[]);
  assert.ok(check.silences.some(s=>s.start<.003&&s.duration>.15&&s.duration<.25),'Keep the whole safe opening lead');
  const active=audio.lines.filter(c=>c.text===clip.text&&c.active!==false);assert.equal(active.length,1);
  for(const key of ['output','sha256','bytes','durationSeconds'])assert.equal(active[0][key],clip[key]);
  assert.equal(active[0].questionRevision,receipt.revision);
  const original=oldAudio.lines.find(c=>c.text===clip.text);assert.equal(original.output,clip.replaces.output);
  restoredAudio.lines[restoredAudio.lines.findIndex(c=>c.text===clip.text)]=original;
  const event=context.contexts.SCHOOL.events[clip.event];assert.equal(event.questionText,clip.text);assert.equal(event.questionAudio,clip.output);
  restoredContext.contexts.SCHOOL.events[clip.event].questionAudio=oldContext.contexts.SCHOOL.events[clip.event].questionAudio;
}
assert.deepEqual(restoredAudio,oldAudio,'Only exactly two question audio records may change');
assert.deepEqual(restoredContext,oldContext,'Only two questionAudio pointers may change; all words/events/contexts immutable');
for(const clip of oldAudio.lines)assert.equal(hash(clip.output),clip.sha256,'Every pre-existing context recording stays unchanged');
const app=read(`${candidate}/app.js`),start=app.indexOf('function normalizeAudioText('),end=app.indexOf('\nfunction finishParticipantTrial(',start);
assert.ok(start>=0&&end>start);
const sandbox=vm.createContext({});
vm.runInContext(`const requestedVoiceProfile='';const PREFERRED_AUDIO_DIR='audio_preferred';const TEACHER_CLASSMATE_GENERATED_ROOT='assets/teacher_classmate/generated/';const HOME_SCHOOL_GENERATED_ROOT='assets/home_school/generated/';const HOME_SCHOOL_REVISED_AUDIO_ROOT='versions/chs-home-school-evelyn-v1/assets/audio-r18/';let canonicalAudioByText=new Map(),canonicalAudioByOriginalSrc=new Map();${app.slice(start,end)};globalThis.api={installCanonicalAudioMap,canonicalAudioPathForText};`,sandbox);
sandbox.api.installCanonicalAudioMap(json(`${candidate}/data/canonical_audio_manifest_evelyn.json`),json(`${candidate}/data/teacher_classmate_audio_manifest.json`),audio);
for(const clip of audio.lines)assert.equal(sandbox.api.canonicalAudioPathForText(clip.text),clip.output);
console.log(JSON.stringify({status:'PASS',baseline,replacedCurrentQuestionMappings:2,captionChanges:0,wholeSentenceCopies:true,oldContextRecordingsUnchanged:oldAudio.lines.length,canonicalMappings:audio.lines.length,newAtRecognized:2,newWordsMatch:2,clippedSamples:0,internalLongSilences:0,listeningStatus:'Human naturalness preview still required before submission'},null,2));
