(function (root) {
  'use strict';
  const yesNo = ['Yes', 'No'];
  const meanAmount = ['A teeny bit mean', 'A little bit mean', 'Very mean'];
  const helperChoices = ['The kid’s mom', 'The kid’s sister'];
  const steps = [
    {id:'group', phase:'Meet the characters', image:'01-group.png', text:'Oh look! Here is a kid.', note:'Opening adapted to the single kid shown on screen.'},
    {id:'kid', phase:'Meet the kid in the middle', image:'02-child.png', text:'This is the kid in the middle. Tap the kid in the middle.', point:'kid', reminder:'This one in the middle is the kid in the middle. Tap the kid in the middle.'},
    {id:'mom', phase:'Meet the mom', image:'03-mom.png', text:'This is the kid’s mom. Tap the kid’s mom.', point:'mom', reminder:'This one on the left is the kid’s mom. Tap the kid’s mom.'},
    {id:'sister', phase:'Meet the sister', image:'04-sister.png', text:'This is the kid’s sister. Tap the kid’s sister.', point:'sister', reminder:'This one on the right is the kid’s sister. Tap the kid’s sister.'},
    {id:'need', phase:'The kid in the middle needs help', text:'Now let’s say that one day the kid in the middle was very sad.'},
    {id:'witness', phase:'Both helpers see', text:'The kid’s mom and the kid’s sister both see that the kid in the middle is sad.'},
    {id:'predict-compare', phase:'Who will help?', text:'Who do you think will help the kid in the middle?', choices:helperChoices, optionActors:['helper1','helper2'], confirmChoice:true, choiceConfirmations:{"The kid’s mom":{"text":"You chose the kid’s mom. Did you mean that the kid’s mom will help the kid in the middle? Yes or No.","choices":["Yes","No"],"actorId":"helper1"},"The kid’s sister":{"text":"You chose the kid’s sister. Did you mean that the kid’s sister will help the kid in the middle? Yes or No.","choices":["Yes","No"],"actorId":"helper2"}}, measure:'Forced-choice prediction', proposed:true, note:'Two-helper forced-choice adaptation; this is not the original Marshall Study 1 individual Yes/No prediction question.'},
    {id:'practice-intro', phase:'“HAVE TO” practice', image:null, text:'Now, sometimes people HAVE TO do things.', captionEmphasis:'HAVE TO', note:'The Evelyn recording uses continuous speech. HAVE TO remains uppercase and italic on screen as an adaptation.'},
    {id:'practice-stop', phase:'Practice · Stop being mean', image:null, visual:'teacher-practice', displayTitle:'Let’s practice!', displaySetup:'A teacher tells you to stop being mean to someone.', displayQuestion:'Do you HAVE TO stop being mean?', text:'When a teacher tells you to stop being mean to someone, do you HAVE TO stop being mean? Yes or No.', choices:yesNo, expected:'Yes', rereadAfterReminder:true, correctFeedback:'That’s right! When a teacher tells you to stop being mean to someone, you HAVE TO stop being mean.', incorrectFeedback:'No, that’s not quite right. When a teacher tells you to stop being mean to someone, you HAVE TO stop being mean. Let’s try that question again.', reminder:'No, that’s not quite right. When a teacher tells you to stop being mean to someone, you HAVE TO stop being mean. Let’s try that question again.', note:'Correct-answer feedback is mandatory. Incorrect answers receive contextual correction and a reread; only the correct answer advances. Brief comprehension practice, not a study outcome. The illustration and split display wording are adaptations. Reminder wording is a draft implementation choice. This compact forced-choice version omits the strength follow-up.'},
    {id:'practice-lie', phase:'Practice · Lie', image:null, visual:'lie-practice', displayTitle:'Let’s practice!', displaySetup:'Someone asks you a question.', displayQuestion:'Do you HAVE TO lie?', text:'When someone asks you a question, do you HAVE TO lie? Yes or No.', choices:yesNo, expected:'No', rereadAfterReminder:true, correctFeedback:'That’s right! When someone asks you a question, you do NOT HAVE TO lie.', incorrectFeedback:'No, that’s not quite right. When someone asks you a question, you do NOT HAVE TO lie. Let’s try that question again.', reminder:'No, that’s not quite right. When someone asks you a question, you do NOT HAVE TO lie. Let’s try that question again.', note:'Correct-answer feedback is mandatory. Incorrect answers receive contextual correction and a reread; only the correct answer advances. Brief comprehension practice, not a study outcome. Reminder wording is a draft implementation choice. This compact forced-choice version omits the strength follow-up.'},
    {id:'practice-end', phase:'Back to our story', image:null, text:'So now, I’m going to ask you some questions about whether people HAVE TO do things.'},
    {id:'obligation-compare', phase:'Who HAS TO help?', text:'Who do you think HAS TO help the kid in the middle?', choices:helperChoices, optionActors:['helper1','helper2'], confirmChoice:true, choiceConfirmations:{"The kid’s mom":{"text":"You chose the kid’s mom. Did you mean that the kid’s mom HAS TO help the kid in the middle? Yes or No.","choices":["Yes","No"],"actorId":"helper1"},"The kid’s sister":{"text":"You chose the kid’s sister. Did you mean that the kid’s sister HAS TO help the kid in the middle? Yes or No.","choices":["Yes","No"],"actorId":"helper2"}}, measure:'Forced-choice obligation', proposed:true, note:'Two-helper forced-choice adaptation; this is not the original Marshall Study 1 individual Yes/No obligation question.'},
    {id:'outcome-summary', phase:'No one helped', displayText:'No one helped the kid in the middle.', outcomeVisual:true, text:'No one helped the kid in the middle.', note:'Standalone outcome statement. Continue after the sentence to hear each helper’s action and the repeated no-one-helped statement.'},
    {id:'outcome', phase:'Each helper did NOT help', displayText:'The kid’s mom did NOT help the kid in the middle.', outcomeCaptions:['The kid’s mom did NOT help the kid in the middle.','The kid’s sister did NOT help the kid in the middle.','No one helped the kid in the middle.'], outcomeVisual:true, text:'The kid’s mom did NOT help the kid in the middle. The kid’s sister did NOT help the kid in the middle. No one helped the kid in the middle.', note:'Every response path reaches this same outcome, regardless of prediction or obligation choices.'},
    {id:'recall-all', phase:'Recall · No one helped', text:'Can you tell me, did either of these people help the kid in the middle?', choices:yesNo, expected:'No', rereadAfterReminder:true, reminder:'Actually, remember, no one helped the kid in the middle. The kid’s mom did NOT help the kid in the middle. The kid’s sister did NOT help the kid in the middle. No one helped the kid in the middle.'},
    {id:'compare', phase:'Who was meaner?', text:'Who was meaner for NOT helping the kid in the middle?', choices:helperChoices, optionActors:['helper1','helper2'], confirmChoice:true, choiceConfirmations:{"The kid’s mom":{"text":"You chose the kid’s mom. Did you mean that the kid’s mom was meaner for NOT helping the kid in the middle? Yes or No.","choices":["Yes","No"],"actorId":"helper1"},"The kid’s sister":{"text":"You chose the kid’s sister. Did you mean that the kid’s sister was meaner for NOT helping the kid in the middle? Yes or No.","choices":["Yes","No"],"actorId":"helper2"}}, measure:'Forced-choice meanness', proposed:true, note:'Comparison adapted to two helpers and an explicit recipient reference. Buttons follow the scene: mom left, sister right.'},
    {id:'compare-helper1-amount', phase:'Selected helper · How mean?', text:'How mean do you think the kid’s mom was for NOT helping the kid in the middle?', choices:meanAmount, when:['compare','The kid’s mom'], measure:'Selected helper meanness strength', proposed:true, note:'Added strength rating for the helper selected as meaner. This follows the comparison and is an adaptation.'},
    {id:'compare-helper2-amount', phase:'Selected helper · How mean?', text:'How mean do you think the kid’s sister was for NOT helping the kid in the middle?', choices:meanAmount, when:['compare','The kid’s sister'], measure:'Selected helper meanness strength', proposed:true, note:'Added strength rating for the helper selected as meaner. This follows the comparison and is an adaptation.'},
    {id:'evaluation-mom', phase:'Individual evaluation · Mom', text:'Do you think it was Mean or Not Mean that the kid’s mom did NOT help the kid in the middle?', choices:['Mean','Not Mean'], measure:'Individual evaluation'},
    {id:'evaluation-mom-amount', phase:'Meanness strength · Mom', text:'How mean do you think the kid’s mom was for NOT helping the kid in the middle?', displayText:'How mean do you think the kid’s mom was for NOT helping the kid in the middle?', choices:meanAmount, when:['evaluation-mom','Mean'], measure:'Individual meanness strength'},
    {id:'evaluation-sister', phase:'Individual evaluation · Sister', text:'Do you think it was Mean or Not Mean that the kid’s sister did NOT help the kid in the middle?', choices:['Mean','Not Mean'], measure:'Individual evaluation'},
    {id:'evaluation-sister-amount', phase:'Meanness strength · Sister', text:'How mean do you think the kid’s sister was for NOT helping the kid in the middle?', displayText:'How mean do you think the kid’s sister was for NOT helping the kid in the middle?', choices:meanAmount, when:['evaluation-sister','Mean'], measure:'Individual meanness strength'},
    {id:'end', phase:'End of this example', image:null, text:'That’s the end of our story. Thank you!', note:'Draft closing wording.'}
  ].map(s => ({image:'05-sad.png', ...s, ...(s.point || s.expected ? {requireCorrect:true, allowBypass:false} : {})}));
  const draft = {variant:'forced-choice', steps, nextIndex(index, answers) { let next=index+1; while(next<steps.length && steps[next].when && answers[steps[next].when[0]] !== steps[next].when[1]) next++; return next; }};
  if(typeof module !== 'undefined' && module.exports) module.exports=draft;
  root.ObligationDraft=draft;
})(typeof globalThis !== 'undefined' ? globalThis : this);
